apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysampleapp
spec:
  replicas: 1
  template:
    metadata:
     name: mysampleapp
     labels:
       run: mysampleservice
       test: mysampleservice
    spec:
      containers:
        - name: mysampleservice
          image: mycluster.icp:8500/default/sampleapp:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: mysampleservice
  labels:
    run: mysampleservice
spec:
  type: NodePort
  selector:
    run: mysampleservice
  ports:
   - protocol: TCP
     nodePort: 31211
     port: 9080
     name: http
